# Generated by Django 3.2.7 on 2021-09-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_student_proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
